-- MySQL Script generated by MySQL Workbench
-- Wed Nov 28 22:10:33 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blueticket
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blueticket
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blueticket` DEFAULT CHARACTER SET latin1 ;
USE `blueticket` ;

-- -----------------------------------------------------
-- Table `blueticket`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blueticket`.`evento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `imagem_principal` VARCHAR(65) NULL DEFAULT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `descricao` LONGTEXT NULL DEFAULT NULL,
  `precobase` FLOAT NOT NULL DEFAULT '0',
  `dia_inicio` DATETIME NOT NULL,
  `dia_fim` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `blueticket`.`ingresso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blueticket`.`ingresso` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_opcao_evento` INT(11) NOT NULL,
  `preco` DOUBLE NOT NULL,
  `dia` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `blueticket`.`opcao_evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blueticket`.`opcao_evento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_evento` INT(11) NOT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  `lote` INT(11) NOT NULL DEFAULT '1',
  `valor` FLOAT NOT NULL,
  `qtd_max` INT(11) NOT NULL DEFAULT '0',
  `dia_inicio` DATETIME NOT NULL,
  `dia_fim` DATETIME NOT NULL,
  `observacao` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk1_idx` (`id_evento` ASC) VISIBLE,
  CONSTRAINT `fk1`
    FOREIGN KEY (`id_evento`)
    REFERENCES `blueticket`.`evento` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `blueticket`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blueticket`.`usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
